# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gNt8NSKVPTHWwpm3Hd38mFR6knqR547C
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import files

# ==============================================================================
# 1. FILE UPLOAD & LOADING
# ==============================================================================
print("Upload your Fast Delivery Agent Reviews CSV file")
uploaded = files.upload()

file_name = list(uploaded.keys())[0]
df = pd.read_csv(file_name)

# ==============================================================================
# 2. DATA OVERVIEW
# ==============================================================================
print("\n" + "="*60)
print("DATASET OVERVIEW")
print("="*60)

print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

print("\nMissing Values:")
print(df.isnull().sum())

print("\nSample Data:")
print(df.head())

# ==============================================================================
# 3. KPI METRICS
# ==============================================================================
print("\n" + "="*60)
print("KEY PERFORMANCE INDICATORS")
print("="*60)

avg_rating = round(df['Rating'].mean(), 2)
avg_delivery = round(df['Delivery Time (min)'].mean(), 2)
total_orders = len(df)

print("Total Orders:", total_orders)
print("Average Rating:", avg_rating)
print("Average Delivery Time:", avg_delivery, "minutes")

# ==============================================================================
# 4. AGENT PERFORMANCE ANALYSIS
# ==============================================================================
agent_summary = df.groupby('Agent Name').agg(
    Avg_Rating=('Rating', 'mean'),
    Avg_Delivery_Time=('Delivery Time (min)', 'mean'),
    Total_Orders=('Rating', 'count')
).reset_index()

print("\nAgent Performance Summary")
print(agent_summary)

# Top Agent
top_agent = agent_summary.loc[
    agent_summary['Avg_Rating'].idxmax()
]

fastest_agent = agent_summary.loc[
    agent_summary['Avg_Delivery_Time'].idxmin()
]

print("\nTop Rated Agent:")
print(top_agent)

print("\nFastest Delivery Agent:")
print(fastest_agent)

# ==============================================================================
# 5. LOCATION ANALYSIS
# ==============================================================================
print("\nLocation Distribution")
print(df['Location'].value_counts())

# ==============================================================================
# 6. ORDER TYPE ANALYSIS
# ==============================================================================
print("\nOrder Type Distribution")
print(df['Order Type'].value_counts())

# ==============================================================================
# 7. VISUALIZATIONS
# ==============================================================================
sns.set_style("whitegrid")

fig, axes = plt.subplots(2, 2, figsize=(15, 10))

# Chart 1
sns.barplot(
    data=agent_summary,
    x='Agent Name',
    y='Avg_Rating',
    ax=axes[0,0]
)

axes[0,0].set_title("Average Rating by Agent")

# Chart 2
sns.barplot(
    data=agent_summary,
    x='Agent Name',
    y='Avg_Delivery_Time',
    ax=axes[0,1]
)

axes[0,1].set_title("Average Delivery Time by Agent")

# Chart 3
sns.countplot(
    data=df,
    x='Agent Name',
    hue='Customer Feedback Type',
    ax=axes[1,0]
)

axes[1,0].set_title("Customer Feedback by Agent")

# Chart 4
df['Order Type'].value_counts().plot(
    kind='pie',
    autopct='%1.1f%%',
    ax=axes[1,1]
)

axes[1,1].set_title("Order Type Distribution")
axes[1,1].set_ylabel("")

plt.tight_layout()
plt.show()

# ==============================================================================
# 8. BUSINESS INSIGHTS
# ==============================================================================
print("\n" + "="*60)
print("BUSINESS INSIGHTS")
print("="*60)

print(f"Average Customer Rating: {avg_rating}")
print(f"Average Delivery Time: {avg_delivery} minutes")

print(
    f"Best Rated Agent: {top_agent['Agent Name']} "
    f"({top_agent['Avg_Rating']:.2f})"
)

print(
    f"Fastest Agent: {fastest_agent['Agent Name']} "
    f"({fastest_agent['Avg_Delivery_Time']:.2f} min)"
)

print("\nProject Completed Successfully!")